compilation fix for clang on MacOS
I needed this change to compile with clang on MacOS. I haven't tested on anything else so caveat emptor.

```
src/curl.cc:127:25: error: implicit instantiation of undefined template 'std::basic_string<char>'
            std::string token = value.v.str;
                        ^
1 error generated.
```